### ISSUE TITLE
Filters reset when clicking 'reset view'

### ISSUE THREAD

**Issue by vandenbergla** [IMISE/snik-cytoscape.js#94] opened 2018-07-18 07:58 UTC
Browser: Chrome 67 on Windows 7

After I deselected some filters and I click 'reset view', all my filters are back on. 
1) It's not quite nice to keep adjusting the filters, therefore I just don't filter at all anymore
2) The filter drop down menu still shows deselected check boxes. Which means that if I want to select filters, I need to 'put them on' and then deselect them (note that every time I perform these actions the drop down menu closes). 

Kind regards,

Liesbeth
Dept. Medical Informatics, University of Amsterdam

**Comment by KonradHoeffner** [comment] 2018-09-28 13:43
Hi Liesbeth,

1. Filters now don't come back when clicking reset view. The problem still persists in star mode though, which issue #98 investigates so I refer to that and close this one here.
2. This is a duplicate of https://github.com/IMISE/snik-cytoscape.js/issues/93 and is solved now.

**Closed by KonradHoeffner** 2018-09-28 13:43 UTC
